spring.application.name=VietGram Admin Portal

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VNEG_System;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8888
